name: My First Workflow
on:
  push:
    branches:
      - main

jobs:
  myFirstJob:
    runs-on: ubuntu-latest
    steps:
      - name: my First Step
        run: printenv
      - name: my Second Step
        run: |
          echo "Amigoscode"
          echo "Hello" > file.txt
          ls
      - name: Sleep Step
        run: sleep 5
      - name: My First Action
        uses: actions/checkout@v5
      - name: ls repo
        run: |
              ls
